{
  lib,
  data ? import ./sunghyun/data.nix,
}:
let
  fraction =
    name: f:
    "  [\"${name}\"] = { x = ${toString f.x}, y = ${toString f.y}, w = ${toString f.w}, h = ${toString f.h} },";
  fractions = lib.concatStringsSep "\n" (lib.mapAttrsToList fraction data.tiles);
  aliases = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (alias: target: "  [\"${alias}\"] = \"${target}\",") data.tileAliases
  );
in
{
  initLua = ''
    -- Generated by nix/hammerspoon.nix. Hammerspoon is the window-placement
    -- engine: one long-lived process holds the Accessibility grant, instead of
    -- one grant per short-lived caller.

    -- The `hs` command line tool talks to a Mach port that only exists once this
    -- module is loaded, so requiring it is what makes the CLI work.
    require("hs.ipc")

    hs.window.animationDuration = 0
    hs.dockIcon(false)
    hs.menuIcon(false)
    -- launchd owns startup; Hammerspoon's own login item would be a second one.
    hs.autoLaunch(false)
    hs.consoleOnTop(false)

    local GAP = ${toString data.tileGap}

    local FRACTIONS = {
    ${fractions}
    }

    local ALIASES = {
    ${aliases}
    }

    local function resolve(name)
      if name == nil then return nil end
      name = string.lower(name)
      name = ALIASES[name] or name
      if name == "fullscreen" then return "fullscreen" end
      if FRACTIONS[name] then return name end
      return nil
    end

    -- screen:frame() is the usable area (menu bar and Dock excluded), so a
    -- window keeps to its own display and never slides under either.
    local function place(win, f)
      local area = win:screen():frame()
      win:setFrame({
        x = area.x + area.w * f.x + GAP,
        y = area.y + area.h * f.y + GAP,
        w = area.w * f.w - GAP * 2,
        h = area.h * f.h - GAP * 2,
      })
    end

    function tile(name)
      local action = resolve(name)
      if action == nil then
        return "failed: unknown tile action: " .. tostring(name)
      end
      if not hs.accessibilityState() then
        return "failed: Accessibility not granted to Hammerspoon (required for window placement)"
      end
      local win = hs.window.focusedWindow()
      if win == nil then
        return "failed: no focused window"
      end
      if action == "fullscreen" then
        win:toggleFullScreen()
        return "ok: fullscreen toggled"
      end
      if win:isFullScreen() then
        return "skipped: focused window is native fullscreen; exit fullscreen (or use tile fullscreen) to tile"
      end
      place(win, FRACTIONS[action])
      return "ok: " .. action
    end

    function tileActions()
      local names = {}
      for name, _ in pairs(FRACTIONS) do table.insert(names, name) end
      table.insert(names, "fullscreen")
      table.sort(names)
      return table.concat(names, " ")
    end

    function accessibilityGranted()
      return hs.accessibilityState()
    end

    -- init.lua is a symlink into /nix/store, so a switch replaces the link
    -- rather than the file; watching the directory is what catches that.
    hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", function()
      hs.reload()
    end):start()
  '';
}
